# Generated by Django 2.2.7 on 2019-11-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdaccountdetail',
            name='time_of_interest',
        ),
        migrations.AddField(
            model_name='fdaccountdetail',
            name='cron_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.CrontabSchedule'),
        ),
        migrations.AddField(
            model_name='fdaccountdetail',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.IntervalSchedule'),
        ),
        migrations.AddField(
            model_name='fdaccountdetail',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.PeriodicTask'),
        ),
    ]
