# Generated by Django 2.2.7 on 2019-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20191124_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdaccountdetail',
            name='rate_of_interest',
            field=models.FloatField(default=0.0),
        ),
    ]
