# Generated by Django 2.2.7 on 2019-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_auto_20191125_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
